packageExtensions:
  argon2@*:
    dependencies:
      node-gyp: ^9.0.0
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.18.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

nodeLinker: pnp
